import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Toaster } from 'sonner';

import { cn } from '@/lib/utils';

import NavBar from '@/components/Navbar';
import Providers from '@/components/Providers';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn('relative h-full font-sans antialiased', inter.className)}
      >
        <Providers>
          <NavBar />
          <main className='relative flex min-h-screen flex-col'>
            <div className='flex-1 flex-grow'>{children}</div>
          </main>
          <Toaster
            position='top-center'
            richColors
          />
        </Providers>
      </body>
    </html>
  );
}
